services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: converter_api
    depends_on:
      - aboba_db
  aboba_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: abobadb
      POSTGRES_USER: aboba
      POSTGRES_PASSWORD: aboba123
    volumes:
      - aboba_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: aboba_db
volumes:
  aboba_data: