services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - REDIS_CONNECTION=rediska:6379
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: converter_api
    depends_on:
      - aboba_db
      - rediska
  
  aboba_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: abobadb
      POSTGRES_USER: aboba
      POSTGRES_PASSWORD: aboba123
    volumes:
      - aboba_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: aboba_db
  
  rediska:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --notify-keyspace-events Ex
    volumes:
      - rediska_data:/data
    container_name: rediska
volumes:
  aboba_data:
  rediska_data: